FROM python:3.13.2

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

EXPOSE 6379

WORKDIR /app/src
CMD ["celery", "-A", "core", "beat", "--loglevel=info"]
