services:
  django:
    container_name: django-container
    build: .
    volumes:
      - .:/app
      - static_volume:/app/src/static
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    container_name: redis-container
    restart: always
    image: redis:latest

  db:
    container_name: db-container
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  celery:
    container_name: celery-worker-container
    build: .
    depends_on:
      - redis
      - db
    env_file:
      - .env
    working_dir: /app/src
    command: ["celery", "-A", "core", "worker", "--loglevel=info"]

  celery-beat:
    container_name: celery-beat-container
    build: .
    depends_on:
      - redis
      - db
    env_file:
      - .env
    working_dir: /app/src
    command: ["celery", "-A", "core", "beat", "--loglevel=info"]

  nginx:
    container_name: nginx-container
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
    ports:
      - "8080:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
