# Generated by Django 5.2.1 on 2025-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturerecord',
            name='time_recorded',
            field=models.DateTimeField(),
        ),
    ]
