# Generated by Django 5.2.1 on 2025-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_tracker', '0002_alter_temperaturerecord_time_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturerecord',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
    ]
