# Generated by Django 5.2.1 on 2025-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_tracker', '0003_temperaturerecord_timezone_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturerecord',
            name='time_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
